# Run Continuous Integration on every push
# This version tests only Python, but on all supported versions of it.
name: python_compatibility_3.8
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python 3.8 eggs
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.eggs
        key: python-compatibility-3.8-eggs

    - name: Run Python tests on 3.8 latest
      run: docker run -v "${GITHUB_WORKSPACE}:/home/muscle3" python:3.8 /bin/bash -c 'cd /home/muscle3 && pip install -U git+https://github.com/yatiml/yatiml.git@develop && pip install git+https://github.com/multiscale/ymmsl-python.git@develop && pip install -U git+https://github.com/vecma-project/qcg-pilotjob.git@develop && make test_python_only'
